global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'maroccocombo@gmail.com'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'

receivers:
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://127.0.0.1:5001/'
        send_resolved: true

  - name: 'email-alerts'
    email_configs:
      - to: 'maroccocombo@gmail.com'
        headers:
          Subject: 'Alertmanager: {{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          StartsAt: {{ .StartsAt }}
          Labels:
          {{ range .Labels.SortedPairs }}  - {{ .Name }}: {{ .Value }}{{ end }}
          {{ end }}

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
