services:
  db:
    image: postgres:13-alpine
    container_name: myproject_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/ # Corrected path
    env_file:
      - ./.env
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "54321:5432"
    restart: unless-stopped

  redis:
    image: redis:6-alpine
    container_name: myproject_redis
    restart: unless-stopped
    ports:
      - "63790:6379"  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: myproject_app   
    restart: unless-stopped
    environment:
      - POETRY_NO_VIRTUALENVS=1
    # command: poetry run gunicorn --bind 0.0.0.0:8000 visitor_system.wsgi:application
    volumes:
      - ./visitor_system:/app/visitor_system
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    expose:
      - "8000"
    env_file:
      - ./.env
    depends_on:     
      - db
      - redis
  celeryworker:
    build:
      context: .
      dockerfile: Dockerfile    
    container_name: myproject_celeryworker
    environment:
      - POETRY_NO_VIRTUALENVS=1
    # Команды запускаются через poetry run    
    command: bash -c "cd /app/visitor_system && poetry run celery -A visitor_system worker --pool=solo -l info"
    volumes:
      - ./visitor_system:/app/visitor_system
      - media_volume:/app/mediafiles
    env_file:
      - ./.env
    depends_on:
      - redis
      - db
      - app
    restart: unless-stopped

  celerybeat:
    build:
      context: .
      dockerfile: Dockerfile    
    container_name: myproject_celerybeat
    environment:
      - POETRY_NO_VIRTUALENVS=1
    # Команды запускаются через poetry run    
    command: bash -c "cd /app/visitor_system && poetry run celery -A visitor_system beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler"
    volumes:
      - ./visitor_system:/app/visitor_system
      - media_volume:/app/mediafiles
    env_file:
      - ./.env
    depends_on:
      - redis
      - db
      - app
    restart: unless-stopped

  nginx:
    image: nginx:stable-alpine
    container_name: myproject_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/etc/nginx/certs # Добавляем монтирование директории с сертификатами
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    depends_on:
      - app
    restart: unless-stopped

volumes:
  postgres_data:
  static_volume:
  media_volume: