version: '3.8'

services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh  # Инициализационный скрипт
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=visitor_system_db  # Используем стандартное имя базы данных
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  visitor_system:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - POSTGRES_USER=visitor_system_user
      - POSTGRES_PASSWORD=Sako2020
      - POSTGRES_DB=visitor_system_db  # Указываем правильное имя базы данных
      - POSTGRES_PORT=5432

volumes:
  postgres_data: