# Generated by Django 5.2.1 on 2025-09-02 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('security', 'Security Guard'), ('receptionist', 'Receptionist'), ('dept_head', 'Department Head'), ('simple_staff', 'Simple Staff'), ('admin', 'Admin')], max_length=20, unique=True)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='role_info', to='auth.group')),
            ],
        ),
    ]
