# Generated by Django 5.2.1 on 2025-09-02 06:01

from django.db import migrations

def populate_roles_and_groups(apps, schema_editor):
    """
    Создает группы и соответствующие им роли.
    """
    Group = apps.get_model('auth', 'Group')
    Role = apps.get_model('authentication', 'Role')

    ROLE_CHOICES = [
        ('security', 'Security Guard'),
        ('receptionist', 'Receptionist'),
        ('dept_head', 'Department Head'),
        ('simple_staff', 'Simple Staff'),
        ('admin', 'Admin'),
    ]

    for role_name, group_name in ROLE_CHOICES:
        group, created = Group.objects.get_or_create(name=group_name)
        Role.objects.create(name=role_name, group=group)

def revert_roles_and_groups(apps, schema_editor):
    """
    Удаляет созданные роли и группы.
    """
    Group = apps.get_model('auth', 'Group')
    Role = apps.get_model('authentication', 'Role')

    ROLE_CHOICES = [
        ('security', 'Security Guard'),
        ('receptionist', 'Receptionist'),
        ('dept_head', 'Department Head'),
        ('simple_staff', 'Simple Staff'),
        ('admin', 'Admin'),
    ]

    for role_name, group_name in ROLE_CHOICES:
        try:
            role = Role.objects.get(name=role_name)
            role.delete()
        except Role.DoesNotExist:
            pass
        try:
            group = Group.objects.get(name=group_name)
            group.delete()
        except Group.DoesNotExist:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_roles_and_groups'),
    ]

    operations = [
        migrations.RunPython(populate_roles_and_groups, revert_roles_and_groups),
    ]
