# Generated by Django 5.2.1 on 2025-09-02 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_populate_roles_and_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('security', 'Security Guard'), ('receptionist', 'Receptionist'), ('dept_head', 'Department Head'), ('simple_staff', 'Simple Staff'), ('admin', 'Admin')], db_index=True, max_length=20, unique=True),
        ),
    ]
