# Generated by Django 5.2.1 on 2025-09-02 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_department_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Название департамента'),
        ),
    ]
