# Generated by Django 5.2.1 on 2025-09-26 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HikDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('host', models.CharField(max_length=255)),
                ('port', models.PositiveIntegerField(default=80)),
                ('username', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=256)),
                ('verify_ssl', models.BooleanField(default=False)),
                ('is_primary', models.BooleanField(default=True)),
                ('doors_json', models.JSONField(blank=True, default=list)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HikAccessTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('enroll_face', 'Enroll Face'), ('revoke_access', 'Revoke Access'), ('sync_status', 'Sync Status')], max_length=32)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(default='queued', max_length=20)),
                ('attempts', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('visit_id', models.IntegerField(blank=True, null=True)),
                ('guest_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hikvision_integration.hikdevice')),
            ],
        ),
        migrations.CreateModel(
            name='HikEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('occurred_at', models.DateTimeField()),
                ('resolved_visit_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hikvision_integration.hikdevice')),
            ],
        ),
        migrations.CreateModel(
            name='HikPersonBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_id', models.IntegerField()),
                ('person_id', models.CharField(max_length=64)),
                ('face_id', models.CharField(blank=True, default='', max_length=64)),
                ('access_from', models.DateTimeField(blank=True, null=True)),
                ('access_to', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hikvision_integration.hikdevice')),
            ],
        ),
        migrations.CreateModel(
            name='HikFaceLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('library_id', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=100)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_libraries', to='hikvision_integration.hikdevice')),
            ],
            options={
                'unique_together': {('device', 'library_id')},
            },
        ),
    ]
