# Generated by Django 5.2.1 on 2025-09-29 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hikvision_integration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HikCentralServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название сервера')),
                ('base_url', models.URLField(verbose_name='URL сервера')),
                ('integration_key', models.CharField(max_length=100, verbose_name='Integration Partner Key')),
                ('integration_secret', models.CharField(max_length=200, verbose_name='Integration Partner Secret')),
                ('username', models.CharField(max_length=128, verbose_name='Пользователь')),
                ('password', models.CharField(max_length=256, verbose_name='Пароль')),
                ('access_token', models.TextField(blank=True, null=True, verbose_name='Access Token')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Токен истекает')),
                ('enabled', models.BooleanField(default=True, verbose_name='Включен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Сервер HikCentral',
                'verbose_name_plural': 'Серверы HikCentral',
            },
        ),
    ]
