# Generated by Django 5.2 on 2025-04-21 09:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО гостя')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Гость',
                'verbose_name_plural': 'Гости',
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.TextField(verbose_name='Цель визита')),
                ('entry_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время входа')),
                ('exit_time', models.DateTimeField(blank=True, null=True, verbose_name='Время выхода')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='departments.department', verbose_name='Департамент назначения')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits_hosted', to=settings.AUTH_USER_MODEL, verbose_name='Принимающий сотрудник')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitors.guest', verbose_name='Гость')),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits_registered', to=settings.AUTH_USER_MODEL, verbose_name='Кем зарегистрирован')),
            ],
            options={
                'verbose_name': 'Визит',
                'verbose_name_plural': 'Визиты',
                'ordering': ['-entry_time'],
            },
        ),
    ]
