# Generated by Django 5.2 on 2025-04-21 12:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='iin',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator(message='ИИН должен состоять ровно из 12 цифр.', regex='^\\d{12}$'), django.core.validators.MinLengthValidator(12), django.core.validators.MaxLengthValidator(12)], verbose_name='ИИН гостя'),
        ),
        migrations.AddField(
            model_name='visit',
            name='employee_contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Контактный тел. сотрудника (для визита)'),
        ),
    ]
