# Generated by Django 5.2 on 2025-04-21 12:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0002_guest_iin_visit_employee_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='iin',
            field=models.CharField(max_length=12, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='ИИН должен состоять ровно из 12 цифр.', regex='^\\d{12}$'), django.core.validators.MinLengthValidator(12), django.core.validators.MaxLengthValidator(12)], verbose_name='ИИН гостя'),
        ),
    ]
