# Generated by Django 5.2 on 2025-04-22 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0003_alter_guest_iin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visit',
            options={'ordering': ['-entry_time'], 'permissions': [('can_view_visit_statistics', 'Может просматривать статистику визитов')], 'verbose_name': 'Визит', 'verbose_name_plural': 'Визиты'},
        ),
    ]
