# Generated by Django 5.2 on 2025-04-22 09:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('visitors', '0004_alter_visit_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Студента (если есть)')),
                ('student_group', models.CharField(blank=True, max_length=100, null=True, verbose_name='Группа (если есть)')),
                ('student_course', models.IntegerField(blank=True, null=True, verbose_name='Курс (если есть)')),
                ('purpose', models.TextField(verbose_name='Цель визита')),
                ('entry_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время входа')),
                ('exit_time', models.DateTimeField(blank=True, null=True, verbose_name='Время выхода')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='departments.department', verbose_name='Департамент назначения')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitors.guest', verbose_name='Посетитель (Гость)')),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_visits_registered', to=settings.AUTH_USER_MODEL, verbose_name='Кем зарегистрирован')),
            ],
            options={
                'verbose_name': 'Визит студента/абитуриента',
                'verbose_name_plural': 'Визиты студентов/абитуриентов',
                'ordering': ['-entry_time'],
            },
        ),
    ]
