# Generated by Django 5.2 on 2025-04-25 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0007_alter_studentvisit_options_alter_visit_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentvisit',
            options={'ordering': ['-entry_time'], 'verbose_name': 'Визит студента/абитуриента', 'verbose_name_plural': 'Визиты студентов/абитуриентов'},
        ),
        migrations.RemoveField(
            model_name='studentvisit',
            name='expected_entry_time',
        ),
        migrations.AlterField(
            model_name='studentvisit',
            name='status',
            field=models.CharField(choices=[('AWAITING', 'Ожидает прибытия'), ('CHECKED_IN', 'В здании'), ('CHECKED_OUT', 'Вышел'), ('CANCELLED', 'Отменен')], default='CHECKED_IN', max_length=20, verbose_name='Статус'),
        ),
    ]
