# Generated by Django 5.2 on 2025-05-06 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0009_visit_consent_acknowledged'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentvisit',
            options={'ordering': ['-entry_time'], 'permissions': [('can_register_student_visit', 'Может регистрировать визиты студентов/абитуриентов')], 'verbose_name': 'Визит студента/абитуриента', 'verbose_name_plural': 'Визиты студентов/абитуриентов'},
        ),
    ]
