# Generated by Django 5.2 on 2025-05-06 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0011_visitpurpose_visitgroup_visit_visit_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitgroup',
            name='department',
        ),
        migrations.RemoveField(
            model_name='visitgroup',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='visitgroup',
            name='purpose',
        ),
        migrations.RemoveField(
            model_name='visitgroup',
            name='registered_by',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='visit_group',
        ),
        migrations.DeleteModel(
            name='VisitPurpose',
        ),
        migrations.DeleteModel(
            name='VisitGroup',
        ),
    ]
