# Generated by Django 5.2.1 on 2025-08-14 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visitors", "0012_remove_visitgroup_department_and_more"),
    ]

    operations = [
        # Indexes for Visit model - frequently filtered fields
        migrations.RunSQL(
            "CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_visit_entry_time ON visitors_visit(entry_time);",
            reverse_sql="DROP INDEX IF EXISTS idx_visit_entry_time;"
        ),
        migrations.RunSQL(
            "CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_visit_status ON visitors_visit(status);",
            reverse_sql="DROP INDEX IF EXISTS idx_visit_status;"
        ),
        migrations.RunSQL(
            "CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_visit_employee_id ON visitors_visit(employee_id);",
            reverse_sql="DROP INDEX IF EXISTS idx_visit_employee_id;"
        ),
        migrations.RunSQL(
            "CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_visit_department_id ON visitors_visit(department_id);",
            reverse_sql="DROP INDEX IF EXISTS idx_visit_department_id;"
        ),
        migrations.RunSQL(
            "CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_visit_guest_id ON visitors_visit(guest_id);",
            reverse_sql="DROP INDEX IF EXISTS idx_visit_guest_id;"
        ),
        
        # Partial index for visits that are currently active (haven't checked out)
        migrations.RunSQL(
            "CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_visit_active ON visitors_visit(status, entry_time) WHERE exit_time IS NULL;",
            reverse_sql="DROP INDEX IF EXISTS idx_visit_active;"
        ),
        
        # Composite indexes for common queries
        migrations.RunSQL(
            "CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_visit_date_status ON visitors_visit(DATE(entry_time), status);",
            reverse_sql="DROP INDEX IF EXISTS idx_visit_date_status;"
        ),
        
        # Indexes for StudentVisit model
        migrations.RunSQL(
            "CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_studentvisit_entry_time ON visitors_studentvisit(entry_time);",
            reverse_sql="DROP INDEX IF EXISTS idx_studentvisit_entry_time;"
        ),
        migrations.RunSQL(
            "CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_studentvisit_status ON visitors_studentvisit(status);",
            reverse_sql="DROP INDEX IF EXISTS idx_studentvisit_status;"
        ),
        migrations.RunSQL(
            "CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_studentvisit_department_id ON visitors_studentvisit(department_id);",
            reverse_sql="DROP INDEX IF EXISTS idx_studentvisit_department_id;"
        ),
        
        # Index for Guest model - IIN field for quick lookups
        migrations.RunSQL(
            "CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_guest_iin ON visitors_guest(iin);",
            reverse_sql="DROP INDEX IF EXISTS idx_guest_iin;"
        ),
    ]
