# Generated by Django 5.2.1 on 2025-05-28 12:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0012_remove_visitgroup_department_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('guest_full_name', models.CharField(max_length=255, verbose_name='ФИО гостя')),
                ('guest_email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email гостя')),
                ('guest_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон гостя')),
                ('guest_photo', models.ImageField(blank=True, null=True, upload_to='guest_photos/', verbose_name='Фото гостя')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_filled', models.BooleanField(default=False, verbose_name='Гость заполнил данные')),
                ('visit_time', models.DateTimeField(blank=True, null=True, verbose_name='Время визита')),
                ('is_registered', models.BooleanField(default=False, verbose_name='Визит зарегистрирован')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Пригласивший сотрудник')),
                ('visit', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitation', to='visitors.visit', verbose_name='Связанный визит')),
            ],
            options={
                'verbose_name': 'Приглашение гостя',
                'verbose_name_plural': 'Приглашения гостей',
            },
        ),
    ]
