# Generated by Django 5.2.1 on 2025-05-28 12:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0013_guestinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestinvitation',
            name='guest_iin',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator(message='ИИН должен состоять ровно из 12 цифр.', regex='^\\d{12}$'), django.core.validators.MinLengthValidator(12), django.core.validators.MaxLengthValidator(12)], verbose_name='ИИН гостя'),
        ),
    ]
