# Generated by Django 5.2.1 on 2025-05-29 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0014_guestinvitation_guest_iin'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('iin', models.CharField(blank=True, max_length=12, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='guest_photos/')),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='visitors.guestinvitation')),
            ],
        ),
    ]
