# Generated by Django 5.2.1 on 2025-06-03 15:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_department_director'),
        ('visitors', '0016_groupinvitation_groupguest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitPurpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название цели визита')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Цель визита',
                'verbose_name_plural': 'Цели визитов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VisitGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(blank=True, help_text="Например, 'Делегация из XYZ', 'Участники конференции ABC'", max_length=255, verbose_name='Название группы/мероприятия')),
                ('purpose_other_text', models.TextField(blank=True, null=True, verbose_name="Уточнение цели (если 'Другое')")),
                ('expected_entry_time', models.DateTimeField(blank=True, null=True, verbose_name='Планируемое время входа группы')),
                ('registration_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время регистрации группы')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечания по группе')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='departments.department', verbose_name='Департамент назначения')),
                ('employee', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_visits_responsible_for', to=settings.AUTH_USER_MODEL, verbose_name='Принимающий сотрудник (основной)')),
                ('registered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_visit_groups', to=settings.AUTH_USER_MODEL, verbose_name='Зарегистрировал группу')),
                ('purpose', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='visitors.visitpurpose', verbose_name='Основная цель визита группы')),
            ],
            options={
                'verbose_name': 'Групповой визит',
                'verbose_name_plural': 'Групповые визиты',
                'ordering': ['-registration_time'],
            },
        ),
        migrations.AddField(
            model_name='visit',
            name='visit_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='visitors.visitgroup', verbose_name='Групповой визит'),
        ),
    ]
