# Generated by Django 5.2.1 on 2025-06-04 05:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_department_director'),
        ('visitors', '0017_visitpurpose_visitgroup_visit_visit_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupinvitation',
            name='department',
        ),
        migrations.RemoveField(
            model_name='groupinvitation',
            name='employee',
        ),
        migrations.CreateModel(
            name='GroupVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=255, verbose_name='Название группы/мероприятия')),
                ('purpose', models.CharField(max_length=255, verbose_name='Цель визита')),
                ('purpose_other_text', models.TextField(blank=True, null=True, verbose_name='Уточнение цели')),
                ('expected_entry_time', models.DateTimeField(verbose_name='Планируемое время входа')),
                ('actual_entry_time', models.DateTimeField(blank=True, null=True, verbose_name='Фактическое время входа')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечания')),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает заполнения'), ('FILLED', 'Заполнено'), ('REGISTERED', 'Зарегистрировано'), ('COMPLETED', 'Завершено'), ('CANCELLED', 'Отменено')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registration_link', models.CharField(max_length=255, unique=True, verbose_name='Ссылка для регистрации')),
                ('registration_link_expires', models.DateTimeField(verbose_name='Срок действия ссылки')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.department', verbose_name='Департамент')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Принимающий сотрудник')),
            ],
            options={
                'verbose_name': 'Групповой визит',
                'verbose_name_plural': 'Групповые визиты',
            },
        ),
        migrations.CreateModel(
            name='GroupVisitGuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('iin', models.CharField(max_length=12, verbose_name='ИИН')),
                ('photo', models.ImageField(upload_to='guest_photos/', verbose_name='Фото 3x4')),
                ('is_registered', models.BooleanField(default=False, verbose_name='Зарегистрирован')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group_visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='visitors.groupvisit')),
            ],
            options={
                'verbose_name': 'Гость группового визита',
                'verbose_name_plural': 'Гости группового визита',
            },
        ),
        migrations.DeleteModel(
            name='GroupGuest',
        ),
        migrations.DeleteModel(
            name='GroupInvitation',
        ),
    ]
