# Generated by Django 5.2.1 on 2025-06-04 05:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0018_remove_groupinvitation_department_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentvisit',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_visits_hosted', to=settings.AUTH_USER_MODEL, verbose_name='Принимающий сотрудник'),
        ),
    ]
