# Generated by Django 5.2.1 on 2025-06-04 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0019_studentvisit_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupvisit',
            name='is_filled',
            field=models.BooleanField(default=False, verbose_name='Группа заполнена'),
        ),
    ]
