# Generated by Django 5.2.1 on 2025-06-04 05:26

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_department_director'),
        ('visitors', '0020_groupvisit_is_filled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupvisitguest',
            name='group_visit',
        ),
        migrations.RemoveField(
            model_name='studentvisit',
            name='employee',
        ),
        migrations.CreateModel(
            name='GroupInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('purpose', models.TextField(verbose_name='Цель визита')),
                ('visit_time', models.DateTimeField(verbose_name='Время визита')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_filled', models.BooleanField(default=False, verbose_name='Группа заполнена')),
                ('is_registered', models.BooleanField(default=False, verbose_name='Визит зарегистрирован')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='departments.department', verbose_name='Департамент назначения')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Пригласивший сотрудник')),
            ],
            options={
                'verbose_name': 'Групповое приглашение',
                'verbose_name_plural': 'Групповые приглашения',
            },
        ),
        migrations.CreateModel(
            name='GroupGuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО гостя')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email гостя')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон гостя')),
                ('iin', models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator(message='ИИН должен состоять ровно из 12 цифр.', regex='^\\d{12}$'), django.core.validators.MinLengthValidator(12), django.core.validators.MaxLengthValidator(12)], verbose_name='ИИН гостя')),
                ('is_filled', models.BooleanField(default=False, verbose_name='Гость заполнил данные')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group_invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='visitors.groupinvitation', verbose_name='Групповое приглашение')),
            ],
            options={
                'verbose_name': 'Гость группы',
                'verbose_name_plural': 'Гости группы',
            },
        ),
        migrations.DeleteModel(
            name='GroupVisit',
        ),
        migrations.DeleteModel(
            name='GroupVisitGuest',
        ),
    ]
