# Generated by Django 5.2.1 on 2025-06-05 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0021_remove_groupvisitguest_group_visit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupinvitation',
            name='exit_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время выхода группы'),
        ),
        migrations.AddField(
            model_name='groupinvitation',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Визит завершен'),
        ),
    ]
