# Generated by Django 5.2.1 on 2025-06-05 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0022_groupinvitation_exit_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupinvitation',
            name='exit_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время выхода'),
        ),
    ]
