# Generated by Django 5.2.1 on 2025-06-05 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0023_alter_groupinvitation_exit_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupguest',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='group_guests/', verbose_name='Фото гостя'),
        ),
    ]
