# Generated by Django 5.2.1 on 2025-06-05 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0024_groupguest_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupinvitation',
            name='group_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название группы'),
        ),
    ]
