# Generated by Django 5.2.1 on 2025-06-05 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_department_director'),
        ('visitors', '0025_groupinvitation_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupinvitation',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='departments.department', verbose_name='Департамент назначения'),
        ),
        migrations.AlterField(
            model_name='groupinvitation',
            name='purpose',
            field=models.TextField(blank=True, null=True, verbose_name='Цель визита'),
        ),
        migrations.AlterField(
            model_name='groupinvitation',
            name='visit_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время визита'),
        ),
    ]
