# Generated by Django 5.2.1 on 2025-08-14 09:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_department_director'),
        ('visitors', '0026_alter_groupinvitation_department_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='studentvisit',
            index=models.Index(fields=['status'], name='student_visit_status_idx'),
        ),
        migrations.AddIndex(
            model_name='studentvisit',
            index=models.Index(fields=['entry_time'], name='student_visit_entry_time_idx'),
        ),
        migrations.AddIndex(
            model_name='studentvisit',
            index=models.Index(fields=['exit_time'], name='student_visit_exit_time_idx'),
        ),
        migrations.AddIndex(
            model_name='studentvisit',
            index=models.Index(fields=['department'], name='student_visit_department_idx'),
        ),
        migrations.AddIndex(
            model_name='studentvisit',
            index=models.Index(fields=['registered_by'], name='stud_visit_reg_by_idx'),
        ),
        migrations.AddIndex(
            model_name='studentvisit',
            index=models.Index(condition=models.Q(('exit_time__isnull', True)), fields=['status'], name='student_visit_active_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['status'], name='visit_status_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['entry_time'], name='visit_entry_time_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['exit_time'], name='visit_exit_time_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['employee'], name='visit_employee_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['department'], name='visit_department_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['visit_group'], name='visit_group_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['guest'], name='visit_guest_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(condition=models.Q(('exit_time__isnull', True)), fields=['status'], name='visit_active_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(condition=models.Q(('status', 'AWAITING')), fields=['status'], name='visit_awaiting_idx'),
        ),
    ]
