# Generated by Django 5.2.1 on 2025-08-19 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0029_fix_iin_encryption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='iin',
        ),
    ]
