# Generated by Django 5.2.5 on 2025-08-22 08:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_department_director'),
        ('visitors', '0030_remove_guest_iin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='studentvisit',
            index=models.Index(fields=['status', 'entry_time'], name='stud_visit_status_entry_idx'),
        ),
        migrations.AddIndex(
            model_name='studentvisit',
            index=models.Index(fields=['department', 'entry_time'], name='stud_visit_dept_entry_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['status', 'entry_time'], name='visit_status_entry_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['department', 'entry_time'], name='visit_dept_entry_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(condition=models.Q(('exit_time__isnull', True)), fields=['department', 'status'], name='visit_active_dept_idx'),
        ),
    ]
