# Generated by Django 5.2.5 on 2025-08-25 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0033_alter_auditlog_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupguest',
            name='iin_encrypted',
            field=models.BinaryField(blank=True, null=True, verbose_name='Зашифрованный ИИН (группа)'),
        ),
        migrations.AddField(
            model_name='groupguest',
            name='iin_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, null=True, verbose_name='Хэш ИИН (группа)'),
        ),
        migrations.AddField(
            model_name='guestinvitation',
            name='guest_iin_encrypted',
            field=models.BinaryField(blank=True, null=True, verbose_name='Зашифрованный ИИН (приглашение)'),
        ),
        migrations.AddField(
            model_name='guestinvitation',
            name='guest_iin_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, null=True, verbose_name='Хэш ИИН (приглашение)'),
        ),
    ]
