# Generated by Django 5.2.1 on 2025-09-02 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0034_groupguest_iin_encrypted_groupguest_iin_hash_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visit',
            options={'ordering': ['-entry_time', '-expected_entry_time'], 'permissions': [('can_view_visit_statistics', 'Может просматривать статистику визитов'), ('can_export_statistics', 'Может экспортировать статистику')], 'verbose_name': 'Визит (к сотруднику/другой)', 'verbose_name_plural': 'Визиты (к сотрудникам/другие)'},
        ),
    ]
