# Generated by Django 5.2.1 on 2025-09-02 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0035_add_export_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Создание'), ('update', 'Обновление'), ('delete', 'Удаление'), ('view', 'Просмотр'), ('login', 'Вход в систему'), ('logout', 'Выход из системы'), ('login_failed', 'Неудачный вход'), ('permission_change', 'Изменение прав')], max_length=20, verbose_name='Действие'),
        ),
    ]
