# Generated by Django 5.2.1 on 2025-09-02 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0036_extend_auditlog_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuditLog',
        ),
    ]
