# Generated by Django 5.2.1 on 2025-09-02 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0037_delete_auditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visit',
            options={'ordering': ['-entry_time', '-expected_entry_time'], 'permissions': [('can_view_visit_statistics', 'Может просматривать статистику визитов')], 'verbose_name': 'Визит (к сотруднику/другой)', 'verbose_name_plural': 'Визиты (к сотрудникам/другие)'},
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время события')),
                ('action', models.CharField(choices=[('create', 'create'), ('update', 'update'), ('view', 'view')], max_length=16, verbose_name='Действие')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('object_id', models.CharField(max_length=64, verbose_name='ID объекта')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User-Agent')),
                ('path', models.CharField(blank=True, max_length=512, null=True, verbose_name='Путь запроса')),
                ('method', models.CharField(blank=True, max_length=10, null=True, verbose_name='HTTP метод')),
                ('changes', models.JSONField(blank=True, null=True, verbose_name='Изменения')),
                ('extra', models.JSONField(blank=True, null=True, verbose_name='Доп. данные')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Аудит событие',
                'verbose_name_plural': 'Аудит события',
                'indexes': [models.Index(fields=['action'], name='audit_action_idx'), models.Index(fields=['model', 'object_id'], name='audit_model_obj_idx')],
            },
        ),
    ]
