# Generated by Django 5.2.1 on 2025-09-02 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0038_alter_visit_options_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Создание'), ('update', 'Обновление'), ('delete', 'Удаление'), ('view', 'Просмотр'), ('login', 'Вход в систему'), ('logout', 'Выход из системы'), ('login_failed', 'Неудачный вход'), ('admin_create', 'Создание в админке'), ('admin_update', 'Обновление в админке'), ('admin_delete', 'Удаление в админке'), ('permission_change', 'Изменение прав'), ('export', 'Экспорт данных'), ('bulk_operation', 'Массовая операция')], max_length=20, verbose_name='Действие'),
        ),
    ]
