# Generated by Django 5.2.1 on 2025-10-02 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0039_update_auditlog_action_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='access_granted',
            field=models.BooleanField(default=False, verbose_name='Доступ предоставлен в HCP'),
        ),
        migrations.AddField(
            model_name='visit',
            name='access_revoked',
            field=models.BooleanField(default=False, verbose_name='Доступ отозван'),
        ),
        migrations.AddField(
            model_name='visit',
            name='entry_count',
            field=models.IntegerField(default=0, verbose_name='Количество проходов (вход)'),
        ),
        migrations.AddField(
            model_name='visit',
            name='exit_count',
            field=models.IntegerField(default=0, verbose_name='Количество проходов (выход)'),
        ),
        migrations.AddField(
            model_name='visit',
            name='first_entry_detected',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Первый проход (вход)'),
        ),
        migrations.AddField(
            model_name='visit',
            name='first_exit_detected',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Первый проход (выход)'),
        ),
    ]
