# Generated by Django 5.2.1 on 2025-10-02 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0040_visit_access_granted_visit_access_revoked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='hikcentral_person_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID персоны в HikCentral'),
        ),
    ]
