# Generated by Django 5.2.1 on 2025-10-03 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0041_visit_hikcentral_person_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='entry_notification_sent',
            field=models.BooleanField(default=False, verbose_name='Уведомление о входе отправлено'),
        ),
        migrations.AddField(
            model_name='visit',
            name='exit_notification_sent',
            field=models.BooleanField(default=False, verbose_name='Уведомление о выходе отправлено'),
        ),
    ]
