# Generated by Django 5.2.1 on 2025-10-14 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0042_add_notification_tracking_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('exit_without_entry', 'Выход без входа'), ('long_stay', 'Долгое пребывание'), ('suspicious_time', 'Доступ в нерабочее время'), ('multiple_failed_access', 'Многократные неудачные попытки'), ('repeated_exit_entry', 'Частые входы/выходы'), ('other', 'Другое')], db_index=True, max_length=50, verbose_name='Тип инцидента')),
                ('severity', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('critical', 'Критический')], db_index=True, default='medium', max_length=20, verbose_name='Уровень важности')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('investigating', 'Расследуется'), ('resolved', 'Решен'), ('false_alarm', 'Ложная тревога')], db_index=True, default='new', max_length=20, verbose_name='Статус')),
                ('description', models.TextField(verbose_name='Описание')),
                ('detected_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время обнаружения')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Время решения')),
                ('resolution_notes', models.TextField(blank=True, null=True, verbose_name='Заметки по решению')),
                ('alert_sent', models.BooleanField(default=False, verbose_name='Alert отправлен')),
                ('alert_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Время отправки alert')),
                ('metadata', models.JSONField(blank=True, null=True, verbose_name='Дополнительные данные')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL, verbose_name='Назначен сотруднику')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_incidents', to='visitors.visit', verbose_name='Визит')),
            ],
            options={
                'verbose_name': 'Security инцидент',
                'verbose_name_plural': 'Security инциденты',
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['-detected_at'], name='incident_detected_idx'), models.Index(fields=['incident_type', '-detected_at'], name='incident_type_date_idx'), models.Index(fields=['severity', 'status'], name='incident_severity_status_idx')],
            },
        ),
    ]
