# Generated by Django 5.2.1 on 2025-05-28 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom_book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='building',
            field=models.CharField(max_length=50, verbose_name='Блок'),
        ),
    ]
