# Generated by Django 5.2.1 on 2025-09-02 09:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom_book', '0002_alter_classroom_building'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='keybooking',
            name='start_time',
            field=models.DateTimeField(db_index=True, verbose_name='Время начала'),
        ),
        migrations.AlterField(
            model_name='keybooking',
            name='status',
            field=models.CharField(choices=[('reserved', 'Забронирован'), ('issued', 'Выдан'), ('returned', 'Возвращен'), ('expired', 'Просрочен'), ('cancelled', 'Отменен')], db_index=True, default='reserved', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddIndex(
            model_name='keybooking',
            index=models.Index(fields=['status'], name='keybooking_status_idx'),
        ),
        migrations.AddIndex(
            model_name='keybooking',
            index=models.Index(fields=['start_time'], name='keybooking_start_time_idx'),
        ),
        migrations.AddIndex(
            model_name='keybooking',
            index=models.Index(fields=['end_time'], name='keybooking_end_time_idx'),
        ),
        migrations.AddIndex(
            model_name='keybooking',
            index=models.Index(fields=['classroom'], name='keybooking_classroom_idx'),
        ),
        migrations.AddIndex(
            model_name='keybooking',
            index=models.Index(fields=['teacher'], name='keybooking_teacher_idx'),
        ),
        migrations.AddIndex(
            model_name='keybooking',
            index=models.Index(fields=['status', 'start_time'], name='keybooking_status_start_idx'),
        ),
        migrations.AddIndex(
            model_name='keybooking',
            index=models.Index(fields=['classroom', 'start_time'], name='keybooking_classroom_start_idx'),
        ),
        migrations.AddIndex(
            model_name='keybooking',
            index=models.Index(fields=['teacher', 'start_time'], name='keybooking_teacher_start_idx'),
        ),
        migrations.AddIndex(
            model_name='keybooking',
            index=models.Index(fields=['is_returned', 'is_cancelled'], name='keybooking_active_idx'),
        ),
    ]
