# Generated by Django 5.2.1 on 2025-09-02 14:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('notification_type', models.CharField(choices=[('visit_approved', 'Визит одобрен'), ('visit_denied', 'Визит отклонен'), ('visit_reminder', 'Напоминание о визите'), ('guest_arrived', 'Гость прибыл'), ('booking_confirmed', 'Бронирование подтверждено'), ('booking_cancelled', 'Бронирование отменено'), ('system', 'Системное уведомление')], default='system', max_length=20, verbose_name='Тип уведомления')),
                ('read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создано')),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('related_object_type', models.CharField(blank=True, max_length=50)),
                ('action_url', models.URLField(blank=True, verbose_name='Ссылка действия')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebPushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(max_length=500, verbose_name='Endpoint')),
                ('p256dh_key', models.CharField(max_length=255, verbose_name='P256DH Key')),
                ('auth_key', models.CharField(max_length=255, verbose_name='Auth Key')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создано')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('device_name', models.CharField(blank=True, max_length=100, verbose_name='Название устройства')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webpush_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'WebPush подписка',
                'verbose_name_plural': 'WebPush подписки',
                'unique_together': {('user', 'endpoint')},
            },
        ),
        migrations.CreateModel(
            name='WebPushMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notifications.notification')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.webpushsubscription')),
            ],
            options={
                'verbose_name': 'WebPush сообщение',
                'verbose_name_plural': 'WebPush сообщения',
                'ordering': ['-sent_at'],
            },
        ),
    ]
