# Generated by Django 5.2.5 on 2025-08-22 08:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime_dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardFilterPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department_id', models.IntegerField(blank=True, null=True)),
                ('period', models.CharField(default='24h', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_presets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пресет фильтров',
                'verbose_name_plural': 'Пресеты фильтров',
                'indexes': [models.Index(fields=['user', 'name'], name='realtime_da_user_id_c5f209_idx')],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
