# Generated by Django 5.2.1 on 2025-08-22 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtime_dashboard', '0002_dashboardfilterpreset'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DashboardFilterPreset',
        ),
    ]
