# Generated by Django 5.2.1 on 2025-08-22 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtime_dashboard', '0003_alter_dashboardmetric_value_default'),
        ('realtime_dashboard', '0003_delete_dashboardfilterpreset'),
    ]

    operations = [
    ]
