# Generated by Django 5.2.5 on 2025-08-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime_dashboard', '0004_merge_20250822_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardmetric',
            name='metric_type',
            field=models.CharField(choices=[('visitors_count', 'Количество посетителей'), ('active_visits', 'Активные визиты'), ('today_registrations', 'Регистрации за сегодня'), ('avg_visit_duration', 'Средняя длительность визита'), ('department_stats', 'Статистика по департаментам'), ('hourly_stats', 'Почасовая статистика'), ('security_alerts', 'Предупреждения безопасности'), ('status_distribution', 'Распределение по статусам'), ('weekly_trend', 'Тренд по дням недели'), ('duration_distribution', 'Распределение по длительности'), ('visitor_type_comparison', 'Сравнение типов посетителей')], max_length=50, verbose_name='Тип метрики'),
        ),
    ]
